### ISSUE TITLE
Yarn build fails

### ISSUE THREAD

**Issue by fadelgaber** [finos/perspective#1045]
## Support Question
Trying to do a fresh install of Perspective.

Once `yarn build` is ran, this error is thrown:

```
Error: Cannot find module 'dotenv'
Require stack:
- /home/fadel/Desktop/Projects/perspective/scripts/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/fadel/Desktop/Projects/perspective/scripts/build.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND'
```

This is the line in `/scripts/build.js`:
`require("dotenv").config({path: "./.perspectiverc"});`

Looks like it's failing to prompt me the 'setup survey' as mentioned in the docs, and then generate the .perspectiverc file.

**Comment by texodus** [comment]
[`dotenv` is a dependency of the project's `package.json`](https://github.com/finos/perspective/blob/master/package.json#L50), so it sounds like you did not install the project via `yarn`.

You may want to review [`yarn`'s "Getting Started" guide](https://yarnpkg.com/getting-started/usage) before you proceed to much further down trying to build Perspective from source
