### ISSUE TITLE
Webpack Example does not build

### ISSUE THREAD

**Issue by hediet** [finos/perspective#1148]
### Steps to Reproduce:
 1. clone perspective
 2. cd examples/webpack
 3. yarn
 4. yarn start

### Expected Result:
It serves the example.

### Actual Result:
```
yarn run v1.22.4
$ webpack-dev-server --open
internal/modules/cjs/loader.js:1068
  throw err;
  ^

Error: Cannot find module '@finos/perspective/dist/esm/config'
Require stack:
- C:\dev\perspective\packages\perspective-webpack-plugin\index.js
- C:\dev\perspective\examples\webpack\webpack.config.js
- C:\dev\perspective\node_modules\webpack-cli\bin\utils\convert-argv.js
- C:\dev\perspective\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1065:15)
    at Function.Module._load (internal/modules/cjs/loader.js:911:27)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (C:\dev\perspective\packages\perspective-webpack-plugin\index.js:13:22)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\dev\\perspective\\packages\\perspective-webpack-plugin\\index.js',
    'C:\\dev\\perspective\\examples\\webpack\\webpack.config.js',
    'C:\\dev\\perspective\\node_modules\\webpack-cli\\bin\\utils\\convert-argv.js',
    'C:\\dev\\perspective\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}
```

### Environment:
e5b6e347333d9d3d22138a25e0992728e07eb8a7, windows 10

**Comment by hediet** [comment]
Oh I guess I have to build that first. The yarn  workspace confused me. Now I get the error that I actually cloned this demo for.
