### ISSUE TITLE
Error: Shadow root cannot be created on a host which already hosts a shadow tree.

### ISSUE THREAD

**Issue by DanielAsher** [finos/perspective#1180]
## Bug Report

I have created a `perspective-viewer`, configured using [these](https://perspective.finos.org/docs/md/installation.html#from-cdn) instructions. This is hosted within a `Vue` component. The datagrid is working well, but when I use the settings to change from `Datagrid` to any other chart type, and back to `Datagrid` I receive the following error in the console:
```
perspective-viewer-datagrid:1 Uncaught DOMException: Failed to execute 'attachShadow' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.
    at HTMLElement.create_shadow_dom (https://unpkg.com/@finos/perspective-viewer-datagrid:1:40328)
    at HTMLElement.connectedCallback (https://unpkg.com/@finos/perspective-viewer-datagrid:1:26197)
    at https://unpkg.com/@finos/perspective-viewer-datagrid:1:19434
    at HTMLElement.create (https://unpkg.com/@finos/perspective-viewer-datagrid:1:19586)
    at HTMLElement._new_view (https://unpkg.com/@finos/perspective-viewer/dist/umd/perspective-viewer.js:37:7148)
    at async HTMLElement._debounce_update (https://unpkg.com/@finos/perspective-viewer/dist/umd/perspective-viewer.js:37:8645)
```

### Steps to Reproduce:
 1. Set up the `perspective-viewer` within a `Vue` component
 2. Change the chart type to `X Chart`
 3. Change the chart type back to `Datagrid`

### Expected Result:
No console error.

### Actual Result:
```
perspective-viewer-datagrid:1 Uncaught DOMException: Failed to execute 'attachShadow' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.
    at HTMLElement.create_shadow_dom (https://unpkg.com/@finos/perspective-viewer-datagrid:1:40328)
    at HTMLElement.connectedCallback (https://unpkg.com/@finos/perspective-viewer-datagrid:1:26197)
    at https://unpkg.com/@finos/perspective-viewer-datagrid:1:19434
    at HTMLElement.create (https://unpkg.com/@finos/perspective-viewer-datagrid:1:19586)
    at HTMLElement._new_view (https://unpkg.com/@finos/perspective-viewer/dist/umd/perspective-viewer.js:37:7148)
    at async HTMLElement._debounce_update (https://unpkg.com/@finos/perspective-viewer/dist/umd/perspective-viewer.js:37:8645)
create_shadow_dom @ perspective-viewer-datagrid:1
connectedCallback @ perspective-viewer-datagrid:1
(anonymous) @ perspective-viewer-datagrid:1
create @ perspective-viewer-datagrid:1
_new_view @ perspective_element.js:510
async function (async)
_new_view @ perspective_element.js:447
(anonymous) @ perspective_element.js:586
y @ debounce.js:95
E @ debounce.js:144
w @ debounce.js:132
setTimeout (async)
(anonymous) @ debounce.js:103
O @ debounce.js:172
(anonymous) @ perspective_element.js:592
_debounce_update @ perspective_element.js:592
_vis_selector_changed @ action_element.js:321
```
### Environment:
v0.5.2 CDN
Chrome 84

**Comment by texodus** [comment]
Thanks for the report!

I'm not an expert on Vue, but the error indicates some initialization logic being executed multiple times, as a side-effect of attaching a `<perspective-viewer>` to the document.  If you can provide a simple Vue example project illustrating the error you're facing, post a link and I will pull it down and see if I can make a recommendation - maybe start with the [perspective `react` example](https://github.com/finos/perspective/tree/master/examples/react)!

**Comment by DanielAsher** [comment]
I have failed to repro this error too. Noob mistake.
