### ISSUE TITLE
ImportError: libpsp.so

### ISSUE THREAD

**Issue by choandrew** [finos/perspective#1216]
Issue:

`import perspective` in Python
yields
```
CRITICAL:root:Failed to import C++ bindings for Perspective probably as it could not be built for your architecture (check install logs for more details).
ImportError: libpsp.so: cannot open shared object file: No such file or directory
    from perspective import Table, PerspectiveManager, PerspectiveTornadoHandler
ImportError: cannot import name 'Table' from 'perspective' (~/.conda/envs/perspective/lib/python3.8/site-packages/perspective/__init__.py)
```

This is likely due to some error between using `pip` and `conda`.
One potential solution would be to update the conda-forge feedstock so that pip is unnecessary.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
arrow-cpp                 0.16.0
boost                     1.72.0
boost-cpp                 1.72.0
cmake                     3.17.0
arrow-cpp                 0.16.0
python                    3.8.2
perspective-python        0.5.5  # although this is from pypi while the rest are from conda-forge
```
</details>

<br/>
Details To Reproduce and System:
<details>

On Ubuntu 18.04.5 LTS

commands to reproduce:
```
conda create -n optmon python=3.8
conda install -c conda-forge cmake boost
conda install -c conda-forge pyarrow=0.16.0
pip install -vv perspective-python
```
This all installs with no issue.

</details>

**Comment by timkpaine** [comment]
please attach the logs from the `pip install` command. I would expect you're installing against `pyarrow==0.17.1` but you have `pyarrow==0.16.0` installed as detailed the [docs](https://perspective.finos.org/docs/md/installation.html#troubleshooting-installation-from-source)

**Comment by choandrew** [comment]
I created a whole new conda environment as detailed above.
Ran with `pip install -vv --no-build-isolation perspective-python`, still with the same error

The logs are here:
[logs.txt](https://github.com/finos/perspective/files/5329468/a.txt)

**Comment by timkpaine** [comment]
Yep its as I described. You can either pick up the currently installed pyarrow version, or update to match the build version, as detailed in the linked docs.

**Comment by choandrew** [comment]
Hey Tim, 
Thank you for the help. I followed your advice and I deleted all instances of `pyarrow` and ran a fresh install of:
```
conda create -n test_environment python=3.8
conda install -c conda-forge cmake boost pyarrow=0.16.0
pip install -vv --no-build-isolation --no-binary perspective-python perspective-python
```

and the logs showed:
```
  -- Found PyArrow: /home/acho/.conda/envs/test_environment/lib/python3.8/site-packages/pyarrow/include (found version "0.16.0")
  CMake Warning at CMakeLists.txt:418 (message):
    PyArrow found: PYTHON_PYARROW_INCLUDE_DIR -
    /home/acho/.conda/envs/test_environment/lib/python3.8/site-packages/pyarrow/include
```

But I am still getting the error with `libpsp.so`.

Is there something else that I am missing? Thank you.

**Comment by timkpaine** [comment]
this is not enough information, please post full logs.

**Comment by choandrew** [comment]
Hey Tim,
Thanks again for the help.
Here are the logs:

My direct command line outputs
[command_line_output.txt](https://github.com/finos/perspective/files/5338000/command_line_output.txt)

Just in case, here is the pip stdout
[pip_pipe_output.txt](https://github.com/finos/perspective/files/5338001/pip_pipe_output.txt)

**Comment by choandrew** [comment]
hey @timkpaine, any guidance on this?
I can't get it installed on this machine

**Comment by timkpaine** [comment]
Please provide link information for libpsp.so and libbinding.so. According to the logs:
"ImportError: libpsp.so: cannot open shared object file: No such file or directory"

**Comment by choandrew** [comment]
Hey Tim,
Thanks for the response. I am not sure what you are referring to by "link information".
How could I provide you with link information?

(I see lines in the logs that says:
`  [ 92%] Linking CXX shared library /tmp/pip-install-gu75uvd1/perspective-python/build/lib.linux-x86_64-3.8/perspective/table/libpsp.so
`
`  [100%] Linking CXX shared library /tmp/pip-install-gu75uvd1/perspective-python/build/lib.linux-x86_64-3.8/perspective/table/libbinding.so
`
is this what you are looking for?)

**Comment by timkpaine** [comment]
run `ldd` on them and see what it returns

**Comment by choandrew** [comment]
Got it. Here you go:

```
acho@ ~/.conda/envs/per/lib/python3.8/site-packages/perspective/table $ ldd libpsp.so
        linux-vdso.so.1 (0x00007ffd87edc000)
        libarrow.so.16 => /home/acho/.conda/envs/per/lib/libarrow.so.16 (0x00007fc742157000)
        libtbb.so => not found
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc741f38000)
        libstdc++.so.6 => /home/acho/.conda/envs/per/lib/libstdc++.so.6 (0x00007fc7436ac000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc741b9a000)
        libgcc_s.so.1 => /home/acho/.conda/envs/per/lib/libgcc_s.so.1 (0x00007fc743696000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc7417a9000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc743612000)
        libaws-cpp-sdk-s3.so => /home/acho/.conda/envs/per/lib/./libaws-cpp-sdk-s3.so (0x00007fc741563000)
        libaws-cpp-sdk-core.so => /home/acho/.conda/envs/per/lib/./libaws-cpp-sdk-core.so (0x00007fc741466000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc741262000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc74105a000)
        libbz2.so.1.0 => /home/acho/.conda/envs/per/lib/./libbz2.so.1.0 (0x00007fc743680000)
        liblz4.so.1 => /home/acho/.conda/envs/per/lib/./liblz4.so.1 (0x00007fc74364a000)
        libsnappy.so.1 => /home/acho/.conda/envs/per/lib/./libsnappy.so.1 (0x00007fc74363f000)
        libz.so.1 => /home/acho/.conda/envs/per/lib/./libz.so.1 (0x00007fc74103a000)
        libzstd.so.1 => /home/acho/.conda/envs/per/lib/./libzstd.so.1 (0x00007fc740f6f000)
        libprotobuf.so.22 => /home/acho/.conda/envs/per/lib/./libprotobuf.so.22 (0x00007fc740cd6000)
        libcurl.so.4 => /home/acho/.conda/envs/per/lib/././libcurl.so.4 (0x00007fc740c47000)
        libcrypto.so.1.1 => /home/acho/.conda/envs/per/lib/././libcrypto.so.1.1 (0x00007fc74097b000)
        libaws-c-event-stream.so.0unstable => /home/acho/.conda/envs/per/lib/././libaws-c-event-stream.so.0unstable (0x00007fc740972000)
        libaws-c-common.so.0unstable => /home/acho/.conda/envs/per/lib/././libaws-c-common.so.0unstable (0x00007fc740951000)
        libnghttp2.so.14 => /home/acho/.conda/envs/per/lib/./././libnghttp2.so.14 (0x00007fc740929000)
        libssh2.so.1 => /home/acho/.conda/envs/per/lib/./././libssh2.so.1 (0x00007fc7408e5000)
        libssl.so.1.1 => /home/acho/.conda/envs/per/lib/./././libssl.so.1.1 (0x00007fc740855000)
        libgssapi_krb5.so.2 => /home/acho/.conda/envs/per/lib/./././libgssapi_krb5.so.2 (0x00007fc740806000)
        libkrb5.so.3 => /home/acho/.conda/envs/per/lib/./././libkrb5.so.3 (0x00007fc74072d000)
        libk5crypto.so.3 => /home/acho/.conda/envs/per/lib/./././libk5crypto.so.3 (0x00007fc74070e000)
        libcom_err.so.3 => /home/acho/.conda/envs/per/lib/./././libcom_err.so.3 (0x00007fc740708000)
        libaws-checksums.so => /home/acho/.conda/envs/per/lib/./././libaws-checksums.so (0x00007fc7406fa000)
        libkrb5support.so.0 => /home/acho/.conda/envs/per/lib/././././libkrb5support.so.0 (0x00007fc7406eb000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fc7404d0000)
```

```
acho@ ~/.conda/envs/per/lib/python3.8/site-packages/perspective/table $ ldd libbinding.so
        linux-vdso.so.1 (0x00007ffd39776000)
        libpsp.so => not found
        libtbb.so => not found
        libstdc++.so.6 => /home/acho/.conda/envs/per/lib/libstdc++.so.6 (0x00007fbf209d9000)
        libgcc_s.so.1 => /home/acho/.conda/envs/per/lib/libgcc_s.so.1 (0x00007fbf209c5000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbf20293000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbf1fef5000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fbf2093f000)
```

seems like a couple of "not found"s

**Comment by timkpaine** [comment]
Can you test this not with conda and see what happens? We don't see this behavior on normal python or python in virtualenv

**Comment by choandrew** [comment]
I removed conda references from my bashrc so that I could use the regular python.

I tried:
```
python3.8 -m pip install cmake
python3.8 -m pip install boost
python3.8 -m pip install pyarrow==0.16.0
python3.8 -m pip install sudo apt-get install libboost-all-dev-vv perspective-python
sudo apt-get install libboost-all-dev
sudo apt-get install cmake
sudo apt install aptitude
sudo apt-get install python-dev
sudo apt-get install python3-dev python3-pip python3-tk python3-lxml python3-six
python3.8 -m pip install perspective-python
```

and got the error

```
    Use python shared libraries
    CMake Warning (dev) at CMakeLists.txt:366 (find_package):
      Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
      Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
      command to set the policy and suppress this warning.

      CMake variable Python_ROOT is set to:

        /usr

      For compatibility, CMake is ignoring the variable.
    This warning is for project developers.  Use -Wno-dev to suppress it.

    CMake Error at /home/acho/.local/lib/python3.8/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
      Could NOT find Python (missing: Python_INCLUDE_DIRS Python_LIBRARIES
      Development Development.Module Development.Embed) (found suitable exact
      version "3.8.0")
    Call Stack (most recent call first):
      /home/acho/.local/lib/python3.8/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
      /home/acho/.local/lib/python3.8/site-packages/cmake/data/share/cmake-3.18/Modules/FindPython/Support.cmake:2966 (find_package_handle_standard_args)
      /home/acho/.local/lib/python3.8/site-packages/cmake/data/share/cmake-3.18/Modules/FindPython.cmake:393 (include)
      CMakeLists.txt:366 (find_package)


    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-build-s4l97_7j/perspective-python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-build-s4l97_7j/perspective-python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-s4l97_7j/perspective-python/setup.py", line 245, in <module>
        setup(
      File "/home/acho/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/acho/.local/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-s4l97_7j/perspective-python/setup.py", line 108, in run
        self.run_cmake()
      File "/tmp/pip-build-s4l97_7j/perspective-python/setup.py", line 128, in run_cmake
        self.build_extension_cmake(ext)
      File "/tmp/pip-build-s4l97_7j/perspective-python/setup.py", line 214, in build_extension_cmake
        subprocess.check_call(
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/acho/.local/bin/cmake', '/tmp/pip-build-s4l97_7j/perspective-python/dist', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-build-s4l97_7j/perspective-python/build/lib.linux-x86_64-3.8/perspective/table', '-DCMAKE_BUILD_TYPE=Release', '-DPSP_CPP_BUILD=1', '-DPSP_WASM_BUILD=0', '-DPSP_PYTHON_BUILD=1', '-DPSP_PYTHON_VERSION=3.8', '-DPython_ADDITIONAL_VERSIONS=3.8', '-DPython_FIND_VERSION=3.8', '-DPSP_PYTHON_ARROWINSTALLDIR=/usr/lib/python3/dist-packages/pyarrow', '-DPython_EXECUTABLE=/usr/bin/python3.8', '-DPython_ROOT_DIR=/usr', '-DPython_ROOT=/usr', '-DPSP_CMAKE_MODULE_PATH=/tmp/pip-build-s4l97_7j/perspective-python/dist/cmake', '-DPSP_CPP_SRC=/tmp/pip-build-s4l97_7j/perspective-python/dist', '-DPSP_PYTHON_SRC=/tmp/pip-build-s4l97_7j/perspective-python/dist/../perspective', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

    ----------------------------------------
Command "/usr/bin/python3.8 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-s4l97_7j/perspective-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7f93p3pg-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-s4l97_7j/perspective-python/
```

If this is a hassle, I can just wait until there is a conda version for 0.5.5
I would like to use 0.5.5 for the async features
