### ISSUE TITLE
Perspective-cli hosting error: input.on_delete is not a function

### ISSUE THREAD

**Issue by mhkeller** [finos/perspective#1405]
### Steps to Reproduce:
 1. Install perspective-cli `npm install -g @finos/perspective-cli
 2. Create any csv file and run `perspective host my-csv.csv` Sample file:

```
name,value
a,2
b,2
c,4
```

### Expected Result:

I expect it to host a server allowing me to see the data

### Actual Result:

It shows this error:

```
Listening on port 8080
TypeError: input.on_delete is not a function
/usr/local/lib/node_modules/@finos/perspective-cli/node_modules/@finos/perspective/dist/cjs/@finos/perspective-cpp/dist/cjs/perspective.cpp.js:85
          throw ex;
          ^

RuntimeError: abort(TypeError: input.on_delete is not a function). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/usr/local/lib/node_modules/@finos/perspective-cli/node_modules/@finos/perspective/dist/cjs/@finos/perspective-cpp/dist/cjs/perspective.cpp.js:700:15)
    at process.emit (events.js:314:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```

### Environment:

MacOs 10.15.7, node versions tested on 16.0.0 and 12.21.0

### Additional Context:

I also tried installing @finso/perspective-cli as a local project dependency and running it with `npx perspective host test.csv` and it produced the same error.

**Comment by sc1f** [comment]
This issue is due to a bitrot in `perspective-cli`—in v0.7.0 we updated the `table` and `view` API to be async, but when I went through and changed the constructors to the async form I must have missed the use of the `table` constructor in `perspective-cli`.

This would be a good first issue for somebody to look at; it's a pretty easy fix and offers a good springboard to familiarize oneself with the development steps for Perspective.

**Comment by mhkeller** [comment]
@sc1f Where is the perspective-cli repo? I don't see the code anywhere.
