### ISSUE TITLE
Cannot jupyter labextension install @finos/perspective-jupyterlab

### ISSUE THREAD

**Issue by aliavni** [finos/perspective#1580]
## Bug Report

I cannot install perspective-jupyterlab with the `jupyter labextension install @finos/perspective-jupyterlab` commend.

### Steps to Reproduce:
 1. Run `jupyter labextension install @finos/perspective-jupyterlab`

### Expected Result:
Install without errors

### Actual Result:
Here is the log file

```
Node v12.22.6

Yarn configuration loaded.
> /usr/local/opt/node@12/bin/npm pack @finos/perspective-jupyterlab
npm notice 
npm notice 📦  @finos/perspective-jupyterlab@1.0.0
npm notice === Tarball Contents === 
npm notice 11.3kB LICENSE      
npm notice 11.6MB dist/index.js
npm notice 2.4kB  package.json 
npm notice 428B   README.md    
npm notice === Tarball Details === 
npm notice name:          @finos/perspective-jupyterlab           
npm notice version:       1.0.0                                   
npm notice filename:      finos-perspective-jupyterlab-1.0.0.tgz  
npm notice package size:  3.0 MB                                  
npm notice unpacked size: 11.6 MB                                 
npm notice shasum:        bcca0914595aa97aa62c8fa5e4a0c3eaf9e158ce
npm notice integrity:     sha512-VCQZUlLGTiLCA[...]CZ06yiqOA+WqQ==
npm notice total files:   4                                       
npm notice 
finos-perspective-jupyterlab-1.0.0.tgz

Node v12.22.6

Yarn configuration loaded.
Building jupyterlab assets (production, minimized)
> node /Users/username/.virtualenvs/jupyter/lib/python3.8/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.76s.

> node /Users/username/.virtualenvs/jupyter/lib/python3.8/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /Users/username/.virtualenvs/jupyter/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.60s.

> node /Users/username/.virtualenvs/jupyter/lib/python3.8/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
assets by status 25.9 MiB [cached] 139 assets
orphan modules 5.64 MiB [orphan] 2226 modules
runtime modules 110 KiB 14 modules
built modules 34.3 MiB (javascript) 4.92 KiB (share-init) 4.92 KiB (consume-shared) [built]
  javascript modules 34.3 MiB
    modules by path ./node_modules/ 34.2 MiB 1134 modules
    modules by path ./build/ 24.6 KiB 2 modules
  provide-module modules 4.92 KiB
    modules by path provide shared module (default) @jupyterlab/ 3.53 KiB 86 modules
    modules by path provide shared module (default) @lumino/ 588 bytes 14 modules
    modules by path provide shared module (default) @jupyter-widgets/ 168 bytes 4 modules
  consume-shared-module modules 4.92 KiB 61 modules
  json modules 8.46 KiB
    modules by path ./node_modules/ajv/lib/refs/*.json 3.12 KiB 2 modules

WARNING in ./node_modules/vega-lite/build/src/index.js 5:0-30
Should not import the named export 'version' (reexported as 'version') from default-exporting module (only default export is available soon)
 @ consume shared module (default) vega-lite@^4.0.2 (strict) (fallback: ./node_modules/vega-lite/build/src/index.js)
 @ ./node_modules/vega-embed/build/vega-embed.module.js 6:0-44 189:15-29
 @ consume shared module (default) vega-embed@^6.2.1 (strict) (fallback: ./node_modules/vega-embed/build/vega-embed.module.js)
 @ ./node_modules/@jupyterlab/vega5-extension/lib/index.js 166:28-48
 @ consume shared module (default) @jupyterlab/vega5-extension@~3.0.5 (strict) (fallback: ./node_modules/@jupyterlab/vega5-extension/lib/index.js)
 @ ./build/index.out.js 171:16-54
 @ ./build/bootstrap.js

WARNING in shared module underscore -> /Users/username/.virtualenvs/jupyter/share/jupyter/lab/staging/node_modules/underscore/modules/index-all.js
No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file, or manually specify version in shared config.

ERROR in 4467.98b70e1e9c0e39499af5.js?v=98b70e1e9c0e39499af5 from Terser
Unexpected token punc «.», expected punc «,» [webpack://./node_modules/@finos/perspective-jupyterlab/dist/index.js:2,9202048][4467.98b70e1e9c0e39499af5.js?v=98b70e1e9c0e39499af5:7,9201306]
    at js_error (/Users/username/.virtualenvs/jupyter/share/jupyter/lab/staging/node_modules/terser/dist/bundle.min.js:548:11)
    at croak (/Users/username/.virtualenvs/jupyter/share/jupyter/lab/staging/node_modules/terser/dist/bundle.min.js:1272:9)
    at token_error (/Users/username/.virtualenvs/jupyter/share/jupyter/lab/staging/node_modules/terser/dist/bundle.min.js:1280:9)
    at expect_token (/Users/username/.virtualenvs/jupyter/share/jupyter/lab/staging/node_modules/terser/dist/bundle.min.js:1293:9)
    at expect (/Users/username/.virtualenvs/jupyter/share/jupyter/lab/staging/node_modules/terser/dist/bundle.min.js:1296:36)
    at object_or_destructuring_ (/Users/username/.virtualenvs/jupyter/share/jupyter/lab/staging/node_modules/terser/dist/bundle.min.js:2590:44)
    at _embed_tokens_wrapper (/Users/username/.virtualenvs/jupyter/share/jupyter/lab/staging/node_modules/terser/dist/bundle.min.js:1337:26)
    at expr_atom (/Users/username/.virtualenvs/jupyter/share/jupyter/lab/staging/node_modules/terser/dist/bundle.min.js:2489:35)
    at maybe_unary (/Users/username/.virtualenvs/jupyter/share/jupyter/lab/staging/node_modules/terser/dist/bundle.min.js:3299:19)
    at expr_ops (/Users/username/.virtualenvs/jupyter/share/jupyter/lab/staging/node_modules/terser/dist/bundle.min.js:3350:24)

webpack 5.23.0 compiled with 1 error and 2 warnings in 92819 ms

asset index.css 16.1 KiB [compared for emit] (name: index)
asset index.js 0 bytes [compared for emit] [minimized] (name: index)
Entrypoint index 16.1 KiB = index.css 16.1 KiB index.js 0 bytes
./node_modules/@jupyterlab/theme-dark-extension/style/index.css 50 bytes [built] [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-dark-extension/style/variables.css 15.3 KiB [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-dark-extension/style/base.css 472 bytes [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-dark-extension/style/index.css 342 bytes [code generated]
webpack 5.23.0 compiled successfully in 4649 ms

asset index.css 15 KiB [compared for emit] (name: index)
asset index.js 0 bytes [compared for emit] [minimized] (name: index)
Entrypoint index 15 KiB = index.css 15 KiB index.js 0 bytes
./node_modules/@jupyterlab/theme-light-extension/style/index.css 50 bytes [built] [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-light-extension/style/variables.css 14.2 KiB [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-light-extension/style/base.css 472 bytes [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-light-extension/style/index.css 342 bytes [code generated]
webpack 5.23.0 compiled successfully in 4644 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/Users/username/.virtualenvs/jupyter/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/Users/username/.virtualenvs/jupyter/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 133, in start
    build(clean_staging=self.should_clean,

  File "/Users/username/.virtualenvs/jupyter/lib/python3.8/site-packages/jupyterlab/commands.py", line 469, in build
    return handler.build(name=name, version=version, static_url=static_url,

  File "/Users/username/.virtualenvs/jupyter/lib/python3.8/site-packages/jupyterlab/commands.py", line 678, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: lab

```

### Environment:
MacOS 11.6
Python 3.8.7 - virtual environment

jupyter --version
```jupyter core     : 4.7.1
jupyter-notebook : 6.2.0
qtconsole        : 5.0.3
ipython          : 7.21.0
ipykernel        : 5.5.0
jupyter client   : 6.1.11
jupyter lab      : 3.0.9
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.2
traitlets        : 5.0.5
```

**Comment by aliavni** [comment]
> Thanks for the report!
> 
> Please try JupyterLab `v3.1.14`, this is the earliest we've tested perspective-python `v1.0.0` (and it works in [binder](http://beta.mybinder.org/v2/gh/finos/perspective/master?urlpath=lab/tree/examples/jupyter-notebooks) as well). I've not seen this particular error but we had similar errors in a different `3.0.x` version related to how these JupyterLab versions stubbed out node.js functions.

Thanks. This worked
