### ISSUE TITLE
Package subpath './dist/pkg/esm/perspective.cpp.wasm' is not defined by "exports" in @finos/perspective/package.json

### ISSUE THREAD

**Issue by spff** [finos/perspective#1792]
### Steps to Reproduce:
```
(base) JimChangs-MacBook-Air:perspective-master jim.chang$ yarn build
yarn run v1.22.15
$ node scripts/build.js
lerna notice cli v3.22.1
lerna notice filter including "@finos/*"
lerna info filter [ '@finos/*' ]
lerna info Executing command in 12 packages: "yarn build"
$ node ../../scripts/run_emsdk.js node ./build.js
$ echo
$ :

configure: cmake /Users/jim.chang/Projects/perspective-master/cpp/perspective -Wno-dev -DCMAKE_BUILD_TYPE=release -DCMAKE_TOOLCHAIN_FILE=/Users/jim.chang/Projects/perspective-master/.emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/Users/jim.chang/Projects/perspective-master/.emsdk/node/14.18.2_64bit/bin/node
Building minimal Apache Arrow
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- No Doxygen found. Documentation won't be built
-- Could NOT find GTestSrc (missing: GTEST_SOURCE_DIR GTEST_INCLUDE_DIR) 
-- Proceeding with version: 2.0.5.v2.0.5
-- CMAKE_CXX_FLAGS:  -std=c++0x -Wall -pedantic -Werror -Wextra -Wno-unused-parameter -stdlib=libc++ -fsigned-char
-- `tests/monster_test.fbs`: add generation of C++ code with '--no-includes;--gen-compare'
-- `tests/monster_test.fbs`: add generation of binary (.bfbs) schema
-- `tests/namespace_test/namespace_test1.fbs`: add generation of C++ code with '--no-includes;--gen-compare;--gen-name-strings'
-- `tests/namespace_test/namespace_test2.fbs`: add generation of C++ code with '--no-includes;--gen-compare;--gen-name-strings'
-- `tests/union_vector/union_vector.fbs`: add generation of C++ code with '--no-includes;--gen-compare;--gen-name-strings'
-- `tests/optional_scalars.fbs`: add generation of C++ code with '--no-includes;--gen-compare'
-- `tests/native_type_test.fbs`: add generation of C++ code with ''
-- `tests/arrays_test.fbs`: add generation of C++ code with '--scoped-enums;--gen-compare'
-- `tests/arrays_test.fbs`: add generation of binary (.bfbs) schema
-- `tests/monster_test.fbs`: add generation of C++ embedded binary schema code with '--no-includes;--gen-compare'
-- `tests/monster_extra.fbs`: add generation of C++ code with '--no-includes;--gen-compare'
-- `samples/monster.fbs`: add generation of C++ code with '--no-includes;--gen-compare'
-- `samples/monster.fbs`: add generation of binary (.bfbs) schema
-- Could NOT find ExprTk (missing: ExprTk_INCLUDE_DIR) 

Building WASM binding
Skipping C++ binding
Skipping Python binding
Building C++ with strict warnings
Building RELEASE

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jim.chang/Projects/perspective-master/cpp/perspective/dist/release
make: make -j8
Consolidate compiler generated dependencies of target re2
[  0%] Built target arrow_fb_files
[  9%] Built target re2
Consolidate compiler generated dependencies of target arrow
[ 61%] Built target arrow
Consolidate compiler generated dependencies of target psp
[ 98%] Built target psp
Consolidate compiler generated dependencies of target perspective_cjs
Consolidate compiler generated dependencies of target perspective_esm
[ 98%] Built target perspective_cjs
[100%] Built target perspective_esm
$ node build.js
 > ../../tools/perspective-build/worker.js:12:42: error: [plugin: webworker] Package subpath './src/js/perspective.worker.js' is not defined by "exports" in /Users/jim.chang/Projects/perspective-master/node_modules/@finos/perspective/package.json
    12 │                     entryPoints: [require.resolve(args.path)],
       ╵                                           ^
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:719:3)
    at resolveExports (node:internal/modules/cjs/loader:483:36)
    at Module._findPath (node:internal/modules/cjs/loader:523:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:925:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at /Users/jim.chang/Projects/perspective-master/tools/perspective-build/worker.js:12:43
    at callback (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:832:34)
    at handleRequest (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:664:36)

   ../../tools/perspective-build/worker.js:7:14: note: This error came from the "onResolve" callback registered here
     7 │         build.onResolve({filter: /worker.js$/}, (args) => {
       ╵               ~~~~~~~~~
    at setup (/Users/jim.chang/Projects/perspective-master/tools/perspective-build/worker.js:7:15)
    at handlePlugins (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:756:23)
    at Object.buildOrServe (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:1044:7)
    at /Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:1895:17
    at new Promise (<anonymous>)
    at Object.build (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:1894:14)
    at Object.build (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:1749:51)
    at build (/Users/jim.chang/Projects/perspective-master/tools/perspective-build/build.js:17:34)
    at Array.map (<anonymous>)

   worker-stub:@finos/perspective/src/js/perspective.worker.js:2:39: note: The plugin "webworker" was triggered by this import
     2 │                     import worker from "@finos/perspective/src/js/perspective.worker.js";
       ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 > ../../tools/perspective-build/worker.js:12:42: error: [plugin: webworker] Package subpath './src/js/perspective.worker.js' is not defined by "exports" in /Users/jim.chang/Projects/perspective-master/node_modules/@finos/perspective/package.json
    12 │                     entryPoints: [require.resolve(args.path)],
       ╵                                           ^
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:719:3)
    at resolveExports (node:internal/modules/cjs/loader:483:36)
    at Module._findPath (node:internal/modules/cjs/loader:523:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:925:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at /Users/jim.chang/Projects/perspective-master/tools/perspective-build/worker.js:12:43
    at callback (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:832:34)
    at handleRequest (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:664:36)

   ../../tools/perspective-build/worker.js:7:14: note: This error came from the "onResolve" callback registered here
     7 │         build.onResolve({filter: /worker.js$/}, (args) => {
       ╵               ~~~~~~~~~
    at setup (/Users/jim.chang/Projects/perspective-master/tools/perspective-build/worker.js:7:15)
    at handlePlugins (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:756:23)
    at Object.buildOrServe (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:1044:7)
    at /Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:1895:17
    at new Promise (<anonymous>)
    at Object.build (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:1894:14)
    at Object.build (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:1749:51)
    at build (/Users/jim.chang/Projects/perspective-master/tools/perspective-build/build.js:17:34)
    at Array.map (<anonymous>)

   worker-stub:@finos/perspective/src/js/perspective.worker.js:2:43: note: The plugin "webworker" was triggered by this import
     2 │                         import worker from "@finos/perspective/src/js/perspective.worker.js";
       ╵                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 > ../../tools/perspective-build/wasm.js:44:33: error: [plugin: wasm] Package subpath './dist/pkg/esm/perspective.cpp.wasm' is not defined by "exports" in /Users/jim.chang/Projects/perspective-master/node_modules/@finos/perspective/package.json
    44 │             const path = require.resolve(args.path);
       ╵                                  ^
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:719:3)
    at resolveExports (node:internal/modules/cjs/loader:483:36)
    at Module._findPath (node:internal/modules/cjs/loader:523:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:925:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at /Users/jim.chang/Projects/perspective-master/tools/perspective-build/wasm.js:44:34
    at callback (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:889:34)
    at handleRequest (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:672:36)

   ../../tools/perspective-build/wasm.js:43:14: note: This error came from the "onLoad" callback registered here
    43 │         build.onLoad({filter: /.*/, namespace: "wasm"}, async (args) => {
       ╵               ~~~~~~
    at setup (/Users/jim.chang/Projects/perspective-master/tools/perspective-build/wasm.js:43:15)
    at handlePlugins (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:756:23)
    at Object.buildOrServe (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:1044:7)
    at /Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:1895:17
    at new Promise (<anonymous>)
    at Object.build (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:1894:14)
    at Object.build (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:1749:51)
    at build (/Users/jim.chang/Projects/perspective-master/tools/perspective-build/build.js:17:34)
    at Array.map (<anonymous>)

   wasm-inline:@finos/perspective/dist/pkg/esm/perspective.cpp.wasm:2:37: note: The plugin "wasm" was triggered by this import
     2 │                     import wasm from "@finos/perspective/dist/pkg/esm/perspective.cpp.wasm";
       ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  dist/esm/perspective.js           14.7kb  100.0%
   ├ src/js/perspective.browser.js   2.6kb   17.8%
   ├ src/js/config/constants.js      2.1kb   14.5%
   ├ src/js/api/table_api.js         1.7kb   11.6%
   ├ src/js/api/client.js            1.7kb   11.4%
   ├ src/js/websocket/client.js      1.4kb    9.7%
   ├ src/js/api/view_api.js          1.2kb    8.2%
   ├ src/js/config/index.js          946b     6.3%
   ├ src/js/api/dispatch.js          936b     6.2%
   ├ src/js/utils.js                 734b     4.9%
   └ src/js/config/settings.js       630b     4.2%

 > ../../tools/perspective-build/wasm.js:44:33: error: [plugin: wasm] Package subpath './dist/pkg/esm/perspective.cpp.wasm' is not defined by "exports" in /Users/jim.chang/Projects/perspective-master/node_modules/@finos/perspective/package.json
    44 │             const path = require.resolve(args.path);
       ╵                                  ^
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:719:3)
    at resolveExports (node:internal/modules/cjs/loader:483:36)
    at Module._findPath (node:internal/modules/cjs/loader:523:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:925:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at /Users/jim.chang/Projects/perspective-master/tools/perspective-build/wasm.js:44:34
    at callback (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:889:34)
    at handleRequest (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:672:36)

   ../../tools/perspective-build/wasm.js:43:14: note: This error came from the "onLoad" callback registered here
    43 │         build.onLoad({filter: /.*/, namespace: "wasm"}, async (args) => {
       ╵               ~~~~~~
    at setup (/Users/jim.chang/Projects/perspective-master/tools/perspective-build/wasm.js:43:15)
    at handlePlugins (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:756:23)
    at Object.buildOrServe (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:1044:7)
    at /Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:1895:17
    at new Promise (<anonymous>)
    at Object.build (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:1894:14)
    at Object.build (/Users/jim.chang/Projects/perspective-master/node_modules/esbuild/lib/main.js:1749:51)
    at build (/Users/jim.chang/Projects/perspective-master/tools/perspective-build/build.js:17:34)
    at Array.map (<anonymous>)

   wasm-stub:@finos/perspective/dist/pkg/esm/perspective.cpp.wasm:2:33: note: The plugin "wasm" was triggered by this import
     2 │                 import wasm from "@finos/perspective/dist/pkg/esm/perspective.cpp.wasm";
       ╵                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn build exited 1 in '@finos/perspective'
lerna ERR! yarn build exited 1 in '@finos/perspective'

Command failed: GODEBUG=asyncpreemptoff=1 lerna exec --scope="@finos/*" -- yarn build
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

### Environment:
```
$ uname -a
Darwin JimChangs-MacBook-Air.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101 arm64

$ node --version
v18.0.0

$ yarn --version
1.22.15

$ python --version
Python 3.9.7

$ cmake --version
cmake version 3.23.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

# Git SHA 6bbcb40e0a4a0c4bf5325088a6138635377db2a4 [6bbcb40e]

$ rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.60.0 (7737e0b5c 2022-04-04)`
```

It works after I manually add
```
        "./dist/pkg/esm/perspective.cpp.wasm": "./dist/pkg/esm/perspective.cpp.wasm",
        "./pkg/cjs/perspective.cpp.wasm": "./dist/pkg/cjs/perspective.cpp.wasm",
        "./src/js/perspective.worker.js": "./src/js/perspective.worker.js"
```

under the package.json's export clause

**Comment by spff** [comment]
Hi @texodus I think I might have misconfigured something or there should be a PR regards to this issue before closing it.

**Comment by texodus** [comment]
#1838
