### ISSUE TITLE
Reference to __dirname causing test failures

### ISSUE THREAD

**Issue by brianblakely** [finos/perspective#1961]
## Support Question

Beginning as of v1.5.0 and continuing to latest as of writing v1.6.5, I am experiencing the below stacktrace when running a Jest-based test suite against a codebase using Perspective:

```
ReferenceError: __dirname is not defined

      at eval (eval at Ue (../../node_modules/@finos/perspective/dist/umd/worker-stub:@finos/perspective/src/js/perspective.worker.js:25:37), <anonymous>:3:2957)
      at Ce.init (eval at Ue (../../node_modules/@finos/perspective/dist/umd/worker-stub:@finos/perspective/src/js/perspective.worker.js:25:37), <anonymous>:34:35727)
      at Ce.process (eval at Ue (../../node_modules/@finos/perspective/dist/umd/worker-stub:@finos/perspective/src/js/perspective.worker.js:25:37), <anonymous>:34:13813)
      at eval (eval at Ue (../../node_modules/@finos/perspective/dist/umd/worker-stub:@finos/perspective/src/js/perspective.worker.js:25:37), <anonymous>:34:35587)
      at Object.n [as postMessage] (../../node_modules/@finos/perspective/dist/umd/worker-stub:@finos/perspective/src/js/perspective.worker.js:11:41)
      at pe.register (../../node_modules/@finos/perspective/src/js/perspective.browser.js:138:22)
```

**Comment by texodus** [comment]
1) Please always provide a repro.
2) You are trying to load the _browser_ version of `@finos/perspective` in a node runtime - this won't work (hasn't ever worked, though error profile may have changed).  Your options are to load the `cjs`/node.js version of this module instead, or you can avoid loading it outside of a browser context at all.
