### ISSUE TITLE
StreamClosedError logged when disconnecting/reconnecting

### ISSUE THREAD

**Issue by 0x26res** [finos/perspective#2132]
### Steps to Reproduce:

1. run the `python-tornado-streaming` example
2. refresh the webpage very quickly (like press CTRL+R very fast)

I found it is easier to reproduce if you reduce the size of the data set, from 2500 to 25 and reduce the `def data_source()` update size as well.

### Expected Result:

it should work fine

### Actual Result:

I can see this error in stdout:

```
2023-03-09 14:52:02,172 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1860' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /opt/pysetup/.venv/lib/python3.10/site-packages/tornado/websocket.py:1090> exception=WebSocketClosedE
rror()>
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 1092, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 1094, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
```

### Environment:

- perspective-python==1.9.4 
- Python 3.10.10
- macOs (but also on docker with `python:3.10.10-slim-bullseye`)

### Additional Context:

This doesn't impact server or the client. But it's an issue for us because we operate perspective in production and ERROR message trigger an alert which is hard to filter.

I believe it comes from a something wrong in how handler/torando.py calls write_message in https://github.com/finos/perspective/blob/master/python/perspective/perspective/handlers/tornado.py#L50

**Comment by 0x26res** [comment]
@texodus thanks for fixing this 👍
