### ISSUE TITLE
Issue with Local setup 

### ISSUE THREAD

**Issue by RajaPoseidon** [finos/perspective#2604]
Hi ,

I tried running perspective locally , it is throwing below error and i am following the steps mentioned in developer guide.

Can you please suggest on how to fix it ?

Regards,
Raja

perspective on  master via  v20.11.0 
❯ yarn    
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
$ npm-run-all postinstall:*
yarn run v1.22.19
$ node tools/perspective-scripts/install_emsdk.mjs
(node:48111) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
-- Installing Emscripten 3.1.48
Already up to date.
/Users/rajamutyala/Desktop/projects/perspective/.emsdk/emsdk: line 46: /Users/rajamutyala/Desktop/projects/perspective/.emsdk/python/3.9.2_64bit/bin/python3: No such file or directory
/Users/rajamutyala/Desktop/projects/perspective/.emsdk/emsdk: line 46: exec: /Users/rajamutyala/Desktop/projects/perspective/.emsdk/python/3.9.2_64bit/bin/python3: cannot execute: No such file or directory
 Uncaught Exception  Command failed: "/Users/rajamutyala/Desktop/projects/perspective/.emsdk/emsdk" "install" "3.1.48"

Error: Command failed: "/Users/rajamutyala/Desktop/projects/perspective/.emsdk/emsdk" "install" "3.1.48"
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at Command.runSync (file:///Users/rajamutyala/Desktop/projects/perspective/tools/perspective-scripts/sh.mjs:178:16)
    at emsdk (file:///Users/rajamutyala/Desktop/projects/perspective/tools/perspective-scripts/install_emsdk.mjs:46:26)
    at toolchain_install (file:///Users/rajamutyala/Desktop/projects/perspective/tools/perspective-scripts/install_emsdk.mjs:52:5)
    at file:///Users/rajamutyala/Desktop/projects/perspective/tools/perspective-scripts/install_emsdk.mjs:72:5
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "postinstall:emsdk" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by RajaPoseidon** [comment]
i tried doing the setup on m1 mac , not sure if it is not compatible
