### ISSUE TITLE
python tornado streaming example error in perspective v3.1.8

### ISSUE THREAD

**Issue by eric-suptime** [finos/perspective#2871]
## Bug Report
Using python3.12, perspective  v3.1.8 raises AttributeError when running the Tornado streaming example.

### Steps to Reproduce:
1. Clone this repo
2. Run `python examples/python-tornado-streaming/server.py`

### Expected Result:

Should run and I can get UI on localhost HTTP.

### Actual Result:

Raises AttributeError
```
> python examples/perspective_demo_tornado_streaming/server.py

Traceback (most recent call last):
  File "/home/ubuntu/ui/examples/perspective_demo_tornado_streaming/server.py", line 125, in <module>
    app = make_app(perspective_server)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ui/examples/perspective_demo_tornado_streaming/server.py", line 105, in make_app
    perspective.handlers.tornado.PerspectiveTornadoHandler,
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'perspective' has no attribute 'handlers'
```

-   OS and version: Ubuntu 24 LTS
-   Platform/language + version: Python 3.12

### Environment:

CPython with poetry

---
thank you

**Comment by texodus** [comment]
The handler packages need to be imported explicitly since #2754. This example has been updated to reflect this.
