### ISSUE TITLE
Filtering float columns leads to "invalid scalar" error

### ISSUE THREAD

**Issue by jdangerx** [finos/perspective#2881]
## Bug Report

Thanks for the very clear instructions on how to report a bug!

### Steps to Reproduce:

1. Clone the [reproduction repository](https://github.com/jdangerx/repro-perspective-float-filter). 
2. `npm install && npm start` and go to `localhost:8080` (or whatever port it ends up being on)
3. Try to filter by score.

### Expected Result:

Filtering works - e.g. `score > 95` should only show the one row where `score` is greater than 95.

### Actual Result:

Filter doesn't apply and you get two errors in the console:

```
Uncaught (in promise) Error: Abort(): Invalid scalar type: 9
    at n.wbg.__wbindgen_error_new (index.js:37571:13)
    at 0096a06a:0x104583
    at 0096a06a:0x1698c1
    at 0096a06a:0x60346
    at 0096a06a:0xb6d0f
    at 0096a06a:0x188aab
    at ye (index.js:36891:6)
    at s2 (index.js:36841:14)
Uncaught (in promise) Error: Abort(): Invalid scalar type: 95
    at n.wbg.__wbindgen_error_new (index.js:37571:13)
    at 0096a06a:0x104583
    at 0096a06a:0x1698c1
    at 0096a06a:0x60346
    at 0096a06a:0xb6d0f
    at 0096a06a:0x188aab
    at ye (index.js:36891:6)
    at s2 (index.js:36841:14)
```
<img width="953" alt="image" src="https://github.com/user-attachments/assets/c084284f-13d3-492a-b726-32659e0e4029" />

-   OS and version: macOS 14.4.1
-   Platform/language + version: client-side javascript - Chrome version 131.0.6778.140 (Official Build) (arm64)

### Environment:

For JavaScript (browser):

-   `@finos/perspective` version: 3.2.0
-   Browser and version: Chrome Version 131.0.6778.140 (Official Build) (arm64)
-   OS: macOS 14.4.1

**Comment by jdangerx** [comment]
Thanks for the quick turnaround!
