### ISSUE TITLE
Can't create bare Dockerfile image with pyarrow==0.15.1 and perspective-python

### ISSUE THREAD

**Issue by lonestriker** [finos/perspective#966]
## Bug Report
Using this basic Dockerfile, I cannot build an image with perspective-python. No matter what versions of cmake I try to use, it still errors out in the cmake command.

### Steps to Reproduce:
 1. Use the following Dockerfile:
```
# Dockerfile
FROM python:3.7
RUN apt-get -y update
RUN apt-get install -y --fix-missing cmake
RUN cmake --version
RUN pip install pyarrow==0.15.1
RUN cmake --version
RUN pip install perspective-python
```
 2. Build the docker image with a command like so:
```
docker image build -t psp:1.0 -f Dockerfile .
```
### Expected Result:
Proper docker image with perspective-python

### Actual Result:
```
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-mhycp9ft/perspective-python/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-install-mhycp9ft/perspective-python/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 182, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-v7yqlvgg/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 213, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-v7yqlvgg/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 198, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-v7yqlvgg/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 250, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-v7yqlvgg/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 143, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 209, in <module>
      cmdclass=dict(build_ext=PSPBuild, sdist=PSPCheckSDist),
    File "/tmp/pip-build-env-v7yqlvgg/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-v7yqlvgg/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 94, in run
      self.run_cmake()
    File "setup.py", line 112, in run_cmake
      self.build_extension_cmake(ext)
    File "setup.py", line 163, in build_extension_cmake
      subprocess.check_call([self.cmake_cmd, os.path.abspath(ext.sourcedir)] + cmake_args, cwd=self.build_temp, env=env, stderr=subprocess.STDOUT)
    File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/bin/cmake', '/tmp/pip-install-mhycp9ft/perspective-python/dist', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-mhycp9ft/perspective-python/build/lib.linux-x86_64-3.7/perspective/table', '-DCMAKE_BUILD_TYPE=Release', '-DPSP_CPP_BUILD=1', '-DPSP_WASM_BUILD=0', '-DPSP_PYTHON_BUILD=1', '-DPSP_PYTHON_VERSION=3.7.6', '-DPYTHON_EXECUTABLE=/usr/local/bin/python', '-DPython_ROOT_DIR=/usr/local', '-DPython_ROOT=/usr/local', '-DPSP_CMAKE_MODULE_PATH=/tmp/pip-install-mhycp9ft/perspective-python/dist/cmake', '-DPSP_CPP_SRC=/tmp/pip-install-mhycp9ft/perspective-python/dist', '-DPSP_PYTHON_SRC=/tmp/pip-install-mhycp9ft/perspective-python/dist/../perspective', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
```

### Environment:
I've tried both Ubuntu and Debian with the same results:
```
# uname -a
Linux ubuntu 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# uname -a
Linux debian 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
```

**Comment by timkpaine** [comment]
can you chance it to be `pip install perspective-python -v` so we can see verbose logs

**Comment by lonestriker** [comment]
I tried with a Dockerfile that looks more like the one in the Perspective repo, same issue.  Attached build log with verbose logging.
```
# Dockerfile
FROM python:3.7
RUN apt-get -y update
RUN apt-get install -y --fix-missing cmake
RUN cmake --version
RUN python3.7 -m pip install pyarrow==0.15.1
RUN cmake --version
RUN python3.7 -m pip install -v perspective-python
```
[build.txt](https://github.com/finos/perspective/files/4316017/build.txt)

**Comment by timkpaine** [comment]
It's complaining you don't have boost installed.
