### ISSUE TITLE
`WebSocketServer` missing from TypeScript mapping

### ISSUE THREAD

**Issue by andyferris** [finos/perspective#971]
### Description of Problem:

We are using Perspective to host tables in our backend TypeScript/node.js project and make them available by a `WebSocketServer`. I would prefer to use `import perspective from '@finos/perspective'` instead of `const perspective = require("@finos/perspective")` to gain all the TypeScript conveniences - however, VS Code/TypeScript complans that `perspective.WebSocketWorker` doesn't exist and the servers don't appear to be in the `index.d.ts` file.

### Potential Solutions:

Add type mappings to all the functions meant to be exposed to backend node.js users (this improves documentation and discoverability, also).

**Comment by zemeolotu** [comment]
While we do try to keep the typings up to date, `perspective` isn't written in typescript and the typings might not always reflect the current api. I'll raise a PR to update the typings to include `WebSocketServer`. 

Also, we welcome any PR's to fix any of these typings inconsistencies, especially from our typescript users like yourself.

Thanks for raising!

**Comment by andyferris** [comment]
Thanks @zemeolotu - that does make sense, and I do appreciate the extra effort it takes.

> Also, we welcome any PR's to fix any of these typings inconsistencies, especially from our typescript users like yourself.

I'd be happy to contribute. :)

On the typescript side - well I'm still getting used to the whole JS ecosystem myself. My largest bottleneck is actually building Perspective so I could do any development - several of us have tried and none of us havet managed to get it to work. Do you have any tips on getting the builds working? (e.g any instructions that work on a clean install of Ubuntu 18.04? Or could you point me to a docker recipe I could leverage?)

**Comment by timkpaine** [comment]
Lots of docker images: https://github.com/finos/perspective/tree/master/docker

Best bet for building js is `PSP_DOCKER=1 yarn build`.

**Comment by andyferris** [comment]
Thanks Tim. Unfortunately, this still doesn't work for me (which I find surprising for a docker build).

First minor gripe being the yarn build script seems to have a problem with trying to build "all":

```
ferris@andy-laptop:~/dev/perspective (master)$ PSP_DOCKER=1 yarn build
yarn run v1.22.4
$ node scripts/build.js
No .perspectiverc, running setup
? Focus (J)avascript, (P)ython, (A)ll? (all)
Invalid project "undefined" selected, running setup
? Focus (J)avascript, (P)ython, (A)ll? (all)
Invalid project "undefined" selected, running setup
? Focus (J)avascript, (P)ython, (A)ll? Javascript
-- Creating emsdk docker image
CMake Warning at CMakeLists.txt:182 (message):
  

  Building WASM binding

  Skipping C++ binding

  Skipping Python binding

  Building C++ with strict warnings

  Building RELEASE

  Skipping Perspective Documentation

...
```

And yet this still fails. After building the dependencies (i.e. a second attempt of the same) I get a problem with psp.async.js:

```
? Focus (J)avascript, (P)ython, (A)ll? Javascript
-- Creating emsdk docker image
CMake Warning at CMakeLists.txt:182 (message):
  

  Building WASM binding

  Skipping C++ binding

  Skipping Python binding

  Building C++ with strict warnings

  Building RELEASE

  Skipping Perspective Documentation


CMake Warning at CMakeLists.txt:45 (message):
  Dependency found - not rebuilding -
  /src/cpp/perspective/obj/rapidjson-build
Call Stack (most recent call first):
  CMakeLists.txt:214 (psp_build_dep)


-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- No Doxygen found. Documentation won't be built
-- Could NOT find GTestSrc (missing: GTEST_SOURCE_DIR GTEST_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:45 (message):
  Dependency found - not rebuilding -
  /src/cpp/perspective/obj/date-build
Call Stack (most recent call first):
  CMakeLists.txt:395 (psp_build_dep)


CMake Warning at CMakeLists.txt:45 (message):
  Dependency found - not rebuilding -
  /src/cpp/perspective/obj/hopscotch-build
Call Stack (most recent call first):
  CMakeLists.txt:396 (psp_build_dep)


CMake Warning at CMakeLists.txt:45 (message):
  Dependency found - not rebuilding -
  /src/cpp/perspective/obj/ordered-map-build
Call Stack (most recent call first):
  CMakeLists.txt:397 (psp_build_dep)


Building minimal Apache Arrow
CMake Warning at CMakeLists.txt:45 (message):
  Dependency found - not rebuilding -
  /src/cpp/perspective/obj/double-conversion-build
Call Stack (most recent call first):
  CMakeLists.txt:404 (psp_build_dep)


CMake Warning at CMakeLists.txt:45 (message):
  Dependency found - not rebuilding -
  /src/cpp/perspective/obj/arrow-build
Call Stack (most recent call first):
  CMakeLists.txt:405 (psp_build_dep)


/usr/local/bin/flatc
/usr/local/bin/flatc
Found Flatbuffers in /usr/local/include
-- Configuring done
-- Generating done
-- Build files have been written to: /src/cpp/perspective/obj
make: ['make', '-j12']
[  1%] Built target arrow_fb_files
[ 48%] Built target arrow
[ 98%] Built target psp
[100%] Built target perspective.async
-- Building psp.async.js
-- Copying WASM file psp.async.wasm
-- Creating wrapped js runtime
Error: Command failed: yarn run buildPath /home/ferris/dev/perspective
/home/ferris/dev/perspective/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

Error: Cannot find module '@finos/perspective-webpack-plugin'
Require stack:
- /home/ferris/dev/perspective/packages/perspective/src/config/common.config.js
- /home/ferris/dev/perspective/packages/perspective/src/config/perspective.config.js
- /home/ferris/dev/perspective/node_modules/webpack-cli/bin/utils/convert-argv.js
- /home/ferris/dev/perspective/node_modules/webpack-cli/bin/cli.js
- /home/ferris/dev/perspective/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (/home/ferris/dev/perspective/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/ferris/dev/perspective/packages/perspective/src/config/common.config.js:3:27)
    at Module._compile (/home/ferris/dev/perspective/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (/home/ferris/dev/perspective/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/ferris/dev/perspective/packages/perspective/src/config/perspective.config.js:2:16)
    at Module._compile (/home/ferris/dev/perspective/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (/home/ferris/dev/perspective/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/home/ferris/dev/perspective/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/home/ferris/dev/perspective/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /home/ferris/dev/perspective/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/ferris/dev/perspective/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /home/ferris/dev/perspective/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/home/ferris/dev/perspective/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /home/ferris/dev/perspective/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/ferris/dev/perspective/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ferris/dev/perspective/packages/perspective/src/config/common.config.js',
    '/home/ferris/dev/perspective/packages/perspective/src/config/perspective.config.js',
    '/home/ferris/dev/perspective/node_modules/webpack-cli/bin/utils/convert-argv.js',
    '/home/ferris/dev/perspective/node_modules/webpack-cli/bin/cli.js',
    '/home/ferris/dev/perspective/node_modules/webpack/bin/webpack.js'
  ]
}
error Command failed with exit code 1.
ERROR: "build:webpack:umd" exited with 1.
error Command failed with exit code 1.
ERROR: "build:webpack" exited with 1.
error Command failed with exit code 1.
$ mkdirp dist && mkdirp obj
$ npm-run-all build:babel:* build:webpack build:webpack:umd:inline
$ babel src/js --source-maps --out-dir dist/esm
Successfully compiled 20 files with Babel.
$ BABEL_MODULE=auto babel dist/obj --source-maps --out-dir dist/cjs
Successfully compiled 1 file with Babel.
$ BABEL_MODULE=auto babel dist/esm --source-maps --out-dir dist/cjs
Successfully compiled 20 files with Babel.
$ npm-run-all -p build:webpack:* 
$ webpack --color --config src/config/perspective.config.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at /home/ferris/dev/perspective/node_modules/lerna/node_modules/execa/index.js:236:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 1,
  killed: false,
  stdout: '$ mkdirp dist && mkdirp obj\n' +
    '$ npm-run-all build:babel:* build:webpack build:webpack:umd:inline\n' +
    '$ babel src/js --source-maps --out-dir dist/esm\n' +
    'Successfully compiled 20 files with Babel.\n' +
    '$ BABEL_MODULE=auto babel dist/obj --source-maps --out-dir dist/cjs\n' +
    'Successfully compiled 1 file with Babel.\n' +
    '$ BABEL_MODULE=auto babel dist/esm --source-maps --out-dir dist/cjs\n' +
    'Successfully compiled 20 files with Babel.\n' +
    '$ npm-run-all -p build:webpack:* \n' +
    '$ webpack --color --config src/config/perspective.config.js\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr: '/home/ferris/dev/perspective/node_modules/webpack-cli/bin/cli.js:93\n' +
    '\t\t\t\tthrow err;\n' +
    '\t\t\t\t^\n' +
    '\n' +
    "Error: Cannot find module '@finos/perspective-webpack-plugin'\n" +
    'Require stack:\n' +
    '- /home/ferris/dev/perspective/packages/perspective/src/config/common.config.js\n' +
    '- /home/ferris/dev/perspective/packages/perspective/src/config/perspective.config.js\n' +
    '- /home/ferris/dev/perspective/node_modules/webpack-cli/bin/utils/convert-argv.js\n' +
    '- /home/ferris/dev/perspective/node_modules/webpack-cli/bin/cli.js\n' +
    '- /home/ferris/dev/perspective/node_modules/webpack/bin/webpack.js\n' +
    '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:690:27)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:852:19)\n' +
    '    at require (/home/ferris/dev/perspective/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)\n' +
    '    at Object.<anonymous> (/home/ferris/dev/perspective/packages/perspective/src/config/common.config.js:3:27)\n' +
    '    at Module._compile (/home/ferris/dev/perspective/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)\n' +
    '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)\n' +
    '    at Module.load (internal/modules/cjs/loader.js:815:32)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:727:14)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:852:19)\n' +
    '    at require (/home/ferris/dev/perspective/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)\n' +
    '    at Object.<anonymous> (/home/ferris/dev/perspective/packages/perspective/src/config/perspective.config.js:2:16)\n' +
    '    at Module._compile (/home/ferris/dev/perspective/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)\n' +
    '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)\n' +
    '    at Module.load (internal/modules/cjs/loader.js:815:32)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:727:14)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:852:19)\n' +
    '    at require (/home/ferris/dev/perspective/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)\n' +
    '    at WEBPACK_OPTIONS (/home/ferris/dev/perspective/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)\n' +
    '    at requireConfig (/home/ferris/dev/perspective/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)\n' +
    '    at /home/ferris/dev/perspective/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at module.exports (/home/ferris/dev/perspective/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)\n' +
    '    at /home/ferris/dev/perspective/node_modules/webpack-cli/bin/cli.js:71:45\n' +
    '    at Object.parse (/home/ferris/dev/perspective/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)\n' +
    '    at /home/ferris/dev/perspective/node_modules/webpack-cli/bin/cli.js:49:8\n' +
    '    at Object.<anonymous> (/home/ferris/dev/perspective/node_modules/webpack-cli/bin/cli.js:366:3)\n' +
    '    at Module._compile (internal/modules/cjs/loader.js:959:30)\n' +
    '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)\n' +
    '    at Module.load (internal/modules/cjs/loader.js:815:32) {\n' +
    "  code: 'MODULE_NOT_FOUND',\n" +
    '  requireStack: [\n' +
    "    '/home/ferris/dev/perspective/packages/perspective/src/config/common.config.js',\n" +
    "    '/home/ferris/dev/perspective/packages/perspective/src/config/perspective.config.js',\n" +
    "    '/home/ferris/dev/perspective/node_modules/webpack-cli/bin/utils/convert-argv.js',\n" +
    "    '/home/ferris/dev/perspective/node_modules/webpack-cli/bin/cli.js',\n" +
    "    '/home/ferris/dev/perspective/node_modules/webpack/bin/webpack.js'\n" +
    '  ]\n' +
    '}\n' +
    'error Command failed with exit code 1.\n' +
    'ERROR: "build:webpack:umd" exited with 1.\n' +
    'error Command failed with exit code 1.\n' +
    'ERROR: "build:webpack" exited with 1.\n' +
    'error Command failed with exit code 1.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run build',
  timedOut: false,
  exitCode: 1
}
Command failed: lerna run build --loglevel silent 
(node:9758) UnhandledPromiseRejectionWarning: Error: Command failed: node scripts/build.js
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at execute (/home/ferris/dev/perspective/scripts/setup.js:11:24)
    at Proxy.write (/home/ferris/dev/perspective/scripts/setup.js:36:17)
    at choose_project (/home/ferris/dev/perspective/scripts/setup.js:193:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:9758) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9758) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
? Use docker for build env? Yes
Invalid project "undefined" selected, running setup
? Focus (J)avascript, (P)ython, (A)ll? python
-- Getting image for image: '' and python: 'python3.7'
EACCES: permission denied, open '/home/ferris/dev/perspective/python/perspective/dist/obj/arrow-src/.git/modules/cpp/submodules/parquet-testing/objects/02/f20a64c8b4a809aafe270ce6a0a91606e57d1d'
(node:10318) UnhandledPromiseRejectionWarning: Error: Command failed: node scripts/build.js
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at execute (/home/ferris/dev/perspective/scripts/setup.js:11:24)
    at Proxy.write (/home/ferris/dev/perspective/scripts/setup.js:36:17)
    at choose_project (/home/ferris/dev/perspective/scripts/setup.js:193:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:10318) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10318) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 2506.68s.
```

Any help would be greatly appreciated!

**Comment by sc1f** [comment]
We should remove the ‘all’ option- it doesn’t actually make sense because the JS and python can’t share the same built dependencies. 

You need to run ‘yarn clean —deps’ before reinstalling. If your build failed in the C++ dependency building stage, the build script doesn’t know the dependencies are corrupted and will try to proceed as normal on a following build. I’m not sure if it’ll help with why it can’t pull the webpack plugin/why that’s the issue, but it’s good practice to clear the dependencies either way
